//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-03/09/2011 06:46 PM(foreman)-)
//


package com.vz.dam.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BufferSize_QNAME = new QName("", "Buffer_size");
    private final static QName _FormatProfile_QNAME = new QName("", "Format_profile");
    private final static QName _VideoFormatList_QNAME = new QName("", "Video_Format_List");
    private final static QName _ColorSpace_QNAME = new QName("", "Color_space");
    private final static QName _FileLastModificationDate_QNAME = new QName("", "File_last_modification_date");
    private final static QName _FormatSettingsMatrix_QNAME = new QName("", "Format_settings__Matrix");
    private final static QName _CodecSettingsMatrix_QNAME = new QName("", "Codec_settings__Matrix");
    private final static QName _FrameRate_QNAME = new QName("", "Frame_rate");
    private final static QName _FormatSettingsMatrixData_QNAME = new QName("", "Format_Settings_Matrix_Data");
    private final static QName _Format_QNAME = new QName("", "Format");
    private final static QName _CountOfVideoStreams_QNAME = new QName("", "Count_of_video_streams");
    private final static QName _SamplingRate_QNAME = new QName("", "Sampling_rate");
    private final static QName _Xyz_QNAME = new QName("", "xyz");
    private final static QName _ID_QNAME = new QName("", "ID");
    private final static QName _ScanType_QNAME = new QName("", "Scan_type");
    private final static QName _FolderName_QNAME = new QName("", "Folder_name");
    private final static QName _File_QNAME = new QName("", "File");
    private final static QName _FrameCount_QNAME = new QName("", "Frame_count");
    private final static QName _PixelAspectRatio_QNAME = new QName("", "Pixel_aspect_ratio");
    private final static QName _KindOfStream_QNAME = new QName("", "Kind_of_stream");
    private final static QName _FormatSettingsGOP_QNAME = new QName("", "Format_settings__GOP");
    private final static QName _FormatSettingsBVOP_QNAME = new QName("", "Format_settings__BVOP");
    private final static QName _OverallBitRate_QNAME = new QName("", "Overall_bit_rate");
    private final static QName _Width_QNAME = new QName("", "Width");
    private final static QName _StreamIdentifier_QNAME = new QName("", "Stream_identifier");
    private final static QName _ChannelS_QNAME = new QName("", "Channel_s_");
    private final static QName _Model_QNAME = new QName("", "model");
    private final static QName _FileCreationDate_QNAME = new QName("", "File_creation_date");
    private final static QName _ScanOrder_QNAME = new QName("", "Scan_order");
    private final static QName _FormatVersion_QNAME = new QName("", "Format_version");
    private final static QName _BitsPixelFrame_QNAME = new QName("", "Bits__Pixel_Frame_");
    private final static QName _Interlacement_QNAME = new QName("", "Interlacement");
    private final static QName _CompleteName_QNAME = new QName("", "Complete_name");
    private final static QName _MaximumBitRate_QNAME = new QName("", "Maximum_bit_rate");
    private final static QName _Duration_QNAME = new QName("", "Duration");
    private final static QName _SamplesCount_QNAME = new QName("", "Samples_count");
    private final static QName _FileLastModificationDateLocal_QNAME = new QName("", "File_last_modification_date__local_");
    private final static QName _CommercialName_QNAME = new QName("", "Commercial_name");
    private final static QName _StreamSize_QNAME = new QName("", "Stream_size");
    private final static QName _FileSize_QNAME = new QName("", "File_size");
    private final static QName _AudioCodecs_QNAME = new QName("", "Audio_codecs");
    private final static QName _Height_QNAME = new QName("", "Height");
    private final static QName _Track_QNAME = new QName("", "track");
    private final static QName _FormatSettings_QNAME = new QName("", "Format_settings");
    private final static QName _Resolution_QNAME = new QName("", "Resolution");
    private final static QName _CodecSettings_QNAME = new QName("", "Codec_settings");
    private final static QName _DelayOriginal_QNAME = new QName("", "Delay_Original");
    private final static QName _FileName_QNAME = new QName("", "File_name");
    private final static QName _CodecExtensionsUsuallyUsed_QNAME = new QName("", "Codec_Extensions_usually_used");
    private final static QName _BitRateMode_QNAME = new QName("", "Bit_rate_mode");
    private final static QName _InternetMediaType_QNAME = new QName("", "Internet_media_type");
    private final static QName _CodecsVideo_QNAME = new QName("", "Codecs_Video");
    private final static QName _FileExtension_QNAME = new QName("", "File_extension");
    private final static QName _EncodedDate_QNAME = new QName("", "encodedDate");
    private final static QName _Colorimetry_QNAME = new QName("", "Colorimetry");
    private final static QName _Standard_QNAME = new QName("", "Standard");
    private final static QName _AudioFormatList_QNAME = new QName("", "Audio_Format_List");
    private final static QName _FileCreationDateLocal_QNAME = new QName("", "File_creation_date__local_");
    private final static QName _CodecProfile_QNAME = new QName("", "Codec_profile");
    private final static QName _DisplayAspectRatio_QNAME = new QName("", "Display_aspect_ratio");
    private final static QName _Delay_QNAME = new QName("", "Delay");
    private final static QName _DelayOrigin_QNAME = new QName("", "Delay__origin");
    private final static QName _VideoFormatWithHintList_QNAME = new QName("", "Video_Format_WithHint_List");
    private final static QName _DelayOriginalSource_QNAME = new QName("", "Delay_Original_Source");
    private final static QName _CodecFamily_QNAME = new QName("", "Codec_Family");
    private final static QName _DelayRelativeToVideo_QNAME = new QName("", "Delay_relative_to_video");
    private final static QName _Make_QNAME = new QName("", "make");
    private final static QName _Count_QNAME = new QName("", "Count");
    private final static QName _FormatExtensionsUsuallyUsed_QNAME = new QName("", "Format_Extensions_usually_used");
    private final static QName _BitDepth_QNAME = new QName("", "Bit_depth");
    private final static QName _AudioFormatWithHintList_QNAME = new QName("", "Audio_Format_WithHint_List");
    private final static QName _Mediainfo_QNAME = new QName("", "Mediainfo");
    private final static QName _CountOfAudioStreams_QNAME = new QName("", "Count_of_audio_streams");
    private final static QName _BitRate_QNAME = new QName("", "Bit_rate");
    private final static QName _CountOfStreamOfThisKind_QNAME = new QName("", "Count_of_stream_of_this_kind");
    private final static QName _DelayOriginalSettings_QNAME = new QName("", "Delay_Original_Settings");
    private final static QName _Codec_QNAME = new QName("", "Codec");
    private final static QName _Video0Delay_QNAME = new QName("", "Video0_delay");
    private final static QName _CompressionMode_QNAME = new QName("", "Compression_mode");
    private final static QName _ChromaSubsampling_QNAME = new QName("", "Chroma_subsampling");
    private final static QName _ProportionOfThisStream_QNAME = new QName("", "Proportion_of_this_stream");
    private final static QName _RecordedDate_QNAME = new QName("", "recordedDate");
    private final static QName _IntraDcPrecision_QNAME = new QName("", "intra_dc_precision");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FileType }
     * 
     */
    public FileType createFileType() {
        return new FileType();
    }

    /**
     * Create an instance of {@link TrackType }
     * 
     */
    public TrackType createTrackType() {
        return new TrackType();
    }

    /**
     * Create an instance of {@link MediainfoType }
     * 
     */
    public MediainfoType createMediainfoType() {
        return new MediainfoType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Buffer_size")
    public JAXBElement<String> createBufferSize(String value) {
        return new JAXBElement<String>(_BufferSize_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Format_profile")
    public JAXBElement<String> createFormatProfile(String value) {
        return new JAXBElement<String>(_FormatProfile_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Video_Format_List")
    public JAXBElement<String> createVideoFormatList(String value) {
        return new JAXBElement<String>(_VideoFormatList_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Color_space")
    public JAXBElement<String> createColorSpace(String value) {
        return new JAXBElement<String>(_ColorSpace_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "File_last_modification_date")
    public JAXBElement<String> createFileLastModificationDate(String value) {
        return new JAXBElement<String>(_FileLastModificationDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Format_settings__Matrix")
    public JAXBElement<String> createFormatSettingsMatrix(String value) {
        return new JAXBElement<String>(_FormatSettingsMatrix_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Codec_settings__Matrix")
    public JAXBElement<String> createCodecSettingsMatrix(String value) {
        return new JAXBElement<String>(_CodecSettingsMatrix_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Frame_rate")
    public JAXBElement<String> createFrameRate(String value) {
        return new JAXBElement<String>(_FrameRate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Format_Settings_Matrix_Data")
    public JAXBElement<String> createFormatSettingsMatrixData(String value) {
        return new JAXBElement<String>(_FormatSettingsMatrixData_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Format")
    public JAXBElement<String> createFormat(String value) {
        return new JAXBElement<String>(_Format_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Count_of_video_streams")
    public JAXBElement<String> createCountOfVideoStreams(String value) {
        return new JAXBElement<String>(_CountOfVideoStreams_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Sampling_rate")
    public JAXBElement<String> createSamplingRate(String value) {
        return new JAXBElement<String>(_SamplingRate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xyz")
    public JAXBElement<String> createXyz(String value) {
        return new JAXBElement<String>(_Xyz_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ID")
    public JAXBElement<String> createID(String value) {
        return new JAXBElement<String>(_ID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Scan_type")
    public JAXBElement<String> createScanType(String value) {
        return new JAXBElement<String>(_ScanType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Folder_name")
    public JAXBElement<String> createFolderName(String value) {
        return new JAXBElement<String>(_FolderName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "File")
    public JAXBElement<FileType> createFile(FileType value) {
        return new JAXBElement<FileType>(_File_QNAME, FileType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Frame_count")
    public JAXBElement<String> createFrameCount(String value) {
        return new JAXBElement<String>(_FrameCount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Pixel_aspect_ratio")
    public JAXBElement<String> createPixelAspectRatio(String value) {
        return new JAXBElement<String>(_PixelAspectRatio_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Kind_of_stream")
    public JAXBElement<String> createKindOfStream(String value) {
        return new JAXBElement<String>(_KindOfStream_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Format_settings__GOP")
    public JAXBElement<String> createFormatSettingsGOP(String value) {
        return new JAXBElement<String>(_FormatSettingsGOP_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Format_settings__BVOP")
    public JAXBElement<String> createFormatSettingsBVOP(String value) {
        return new JAXBElement<String>(_FormatSettingsBVOP_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Overall_bit_rate")
    public JAXBElement<String> createOverallBitRate(String value) {
        return new JAXBElement<String>(_OverallBitRate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Width")
    public JAXBElement<String> createWidth(String value) {
        return new JAXBElement<String>(_Width_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Stream_identifier")
    public JAXBElement<String> createStreamIdentifier(String value) {
        return new JAXBElement<String>(_StreamIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Channel_s_")
    public JAXBElement<String> createChannelS(String value) {
        return new JAXBElement<String>(_ChannelS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "model")
    public JAXBElement<String> createModel(String value) {
        return new JAXBElement<String>(_Model_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "File_creation_date")
    public JAXBElement<String> createFileCreationDate(String value) {
        return new JAXBElement<String>(_FileCreationDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Scan_order")
    public JAXBElement<String> createScanOrder(String value) {
        return new JAXBElement<String>(_ScanOrder_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Format_version")
    public JAXBElement<String> createFormatVersion(String value) {
        return new JAXBElement<String>(_FormatVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Bits__Pixel_Frame_")
    public JAXBElement<String> createBitsPixelFrame(String value) {
        return new JAXBElement<String>(_BitsPixelFrame_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Interlacement")
    public JAXBElement<String> createInterlacement(String value) {
        return new JAXBElement<String>(_Interlacement_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Complete_name")
    public JAXBElement<String> createCompleteName(String value) {
        return new JAXBElement<String>(_CompleteName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Maximum_bit_rate")
    public JAXBElement<String> createMaximumBitRate(String value) {
        return new JAXBElement<String>(_MaximumBitRate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Duration")
    public JAXBElement<String> createDuration(String value) {
        return new JAXBElement<String>(_Duration_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Samples_count")
    public JAXBElement<String> createSamplesCount(String value) {
        return new JAXBElement<String>(_SamplesCount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "File_last_modification_date__local_")
    public JAXBElement<String> createFileLastModificationDateLocal(String value) {
        return new JAXBElement<String>(_FileLastModificationDateLocal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Commercial_name")
    public JAXBElement<String> createCommercialName(String value) {
        return new JAXBElement<String>(_CommercialName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Stream_size")
    public JAXBElement<String> createStreamSize(String value) {
        return new JAXBElement<String>(_StreamSize_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "File_size")
    public JAXBElement<String> createFileSize(String value) {
        return new JAXBElement<String>(_FileSize_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Audio_codecs")
    public JAXBElement<String> createAudioCodecs(String value) {
        return new JAXBElement<String>(_AudioCodecs_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Height")
    public JAXBElement<String> createHeight(String value) {
        return new JAXBElement<String>(_Height_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrackType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "track")
    public JAXBElement<TrackType> createTrack(TrackType value) {
        return new JAXBElement<TrackType>(_Track_QNAME, TrackType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Format_settings")
    public JAXBElement<String> createFormatSettings(String value) {
        return new JAXBElement<String>(_FormatSettings_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Resolution")
    public JAXBElement<String> createResolution(String value) {
        return new JAXBElement<String>(_Resolution_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Codec_settings")
    public JAXBElement<String> createCodecSettings(String value) {
        return new JAXBElement<String>(_CodecSettings_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Delay_Original")
    public JAXBElement<String> createDelayOriginal(String value) {
        return new JAXBElement<String>(_DelayOriginal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "File_name")
    public JAXBElement<String> createFileName(String value) {
        return new JAXBElement<String>(_FileName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Codec_Extensions_usually_used")
    public JAXBElement<String> createCodecExtensionsUsuallyUsed(String value) {
        return new JAXBElement<String>(_CodecExtensionsUsuallyUsed_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Bit_rate_mode")
    public JAXBElement<String> createBitRateMode(String value) {
        return new JAXBElement<String>(_BitRateMode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Internet_media_type")
    public JAXBElement<String> createInternetMediaType(String value) {
        return new JAXBElement<String>(_InternetMediaType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Codecs_Video")
    public JAXBElement<String> createCodecsVideo(String value) {
        return new JAXBElement<String>(_CodecsVideo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "File_extension")
    public JAXBElement<String> createFileExtension(String value) {
        return new JAXBElement<String>(_FileExtension_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "encodedDate")
    public JAXBElement<String> createEncodedDate(String value) {
        return new JAXBElement<String>(_EncodedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Colorimetry")
    public JAXBElement<String> createColorimetry(String value) {
        return new JAXBElement<String>(_Colorimetry_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Standard")
    public JAXBElement<String> createStandard(String value) {
        return new JAXBElement<String>(_Standard_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Audio_Format_List")
    public JAXBElement<String> createAudioFormatList(String value) {
        return new JAXBElement<String>(_AudioFormatList_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "File_creation_date__local_")
    public JAXBElement<String> createFileCreationDateLocal(String value) {
        return new JAXBElement<String>(_FileCreationDateLocal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Codec_profile")
    public JAXBElement<String> createCodecProfile(String value) {
        return new JAXBElement<String>(_CodecProfile_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Display_aspect_ratio")
    public JAXBElement<String> createDisplayAspectRatio(String value) {
        return new JAXBElement<String>(_DisplayAspectRatio_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Delay")
    public JAXBElement<String> createDelay(String value) {
        return new JAXBElement<String>(_Delay_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Delay__origin")
    public JAXBElement<String> createDelayOrigin(String value) {
        return new JAXBElement<String>(_DelayOrigin_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Video_Format_WithHint_List")
    public JAXBElement<String> createVideoFormatWithHintList(String value) {
        return new JAXBElement<String>(_VideoFormatWithHintList_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Delay_Original_Source")
    public JAXBElement<String> createDelayOriginalSource(String value) {
        return new JAXBElement<String>(_DelayOriginalSource_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Codec_Family")
    public JAXBElement<String> createCodecFamily(String value) {
        return new JAXBElement<String>(_CodecFamily_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Delay_relative_to_video")
    public JAXBElement<String> createDelayRelativeToVideo(String value) {
        return new JAXBElement<String>(_DelayRelativeToVideo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "make")
    public JAXBElement<String> createMake(String value) {
        return new JAXBElement<String>(_Make_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Count")
    public JAXBElement<String> createCount(String value) {
        return new JAXBElement<String>(_Count_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Format_Extensions_usually_used")
    public JAXBElement<String> createFormatExtensionsUsuallyUsed(String value) {
        return new JAXBElement<String>(_FormatExtensionsUsuallyUsed_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Bit_depth")
    public JAXBElement<String> createBitDepth(String value) {
        return new JAXBElement<String>(_BitDepth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Audio_Format_WithHint_List")
    public JAXBElement<String> createAudioFormatWithHintList(String value) {
        return new JAXBElement<String>(_AudioFormatWithHintList_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediainfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Mediainfo")
    public JAXBElement<MediainfoType> createMediainfo(MediainfoType value) {
        return new JAXBElement<MediainfoType>(_Mediainfo_QNAME, MediainfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Count_of_audio_streams")
    public JAXBElement<String> createCountOfAudioStreams(String value) {
        return new JAXBElement<String>(_CountOfAudioStreams_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Bit_rate")
    public JAXBElement<String> createBitRate(String value) {
        return new JAXBElement<String>(_BitRate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Count_of_stream_of_this_kind")
    public JAXBElement<String> createCountOfStreamOfThisKind(String value) {
        return new JAXBElement<String>(_CountOfStreamOfThisKind_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Delay_Original_Settings")
    public JAXBElement<String> createDelayOriginalSettings(String value) {
        return new JAXBElement<String>(_DelayOriginalSettings_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Codec")
    public JAXBElement<String> createCodec(String value) {
        return new JAXBElement<String>(_Codec_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Video0_delay")
    public JAXBElement<String> createVideo0Delay(String value) {
        return new JAXBElement<String>(_Video0Delay_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Compression_mode")
    public JAXBElement<String> createCompressionMode(String value) {
        return new JAXBElement<String>(_CompressionMode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Chroma_subsampling")
    public JAXBElement<String> createChromaSubsampling(String value) {
        return new JAXBElement<String>(_ChromaSubsampling_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Proportion_of_this_stream")
    public JAXBElement<String> createProportionOfThisStream(String value) {
        return new JAXBElement<String>(_ProportionOfThisStream_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "recordedDate")
    public JAXBElement<String> createRecordedDate(String value) {
        return new JAXBElement<String>(_RecordedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "intra_dc_precision")
    public JAXBElement<String> createIntraDcPrecision(String value) {
        return new JAXBElement<String>(_IntraDcPrecision_QNAME, String.class, null, value);
    }

}
