//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-03/09/2011 06:46 PM(foreman)-)
//


package com.vz.dam.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for trackType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="trackType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Count"/>
 *         &lt;element ref="{}Count_of_stream_of_this_kind"/>
 *         &lt;element ref="{}Kind_of_stream" maxOccurs="unbounded"/>
 *         &lt;element ref="{}Stream_identifier" maxOccurs="unbounded"/>
 *         &lt;choice>
 *           &lt;element ref="{}Count_of_video_streams" minOccurs="0"/>
 *           &lt;element ref="{}ID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{}Count_of_audio_streams" minOccurs="0"/>
 *         &lt;element ref="{}Video_Format_List" minOccurs="0"/>
 *         &lt;element ref="{}Video_Format_WithHint_List" minOccurs="0"/>
 *         &lt;element ref="{}Codecs_Video" minOccurs="0"/>
 *         &lt;element ref="{}Audio_Format_List" minOccurs="0"/>
 *         &lt;element ref="{}Audio_Format_WithHint_List" minOccurs="0"/>
 *         &lt;element ref="{}Audio_codecs" minOccurs="0"/>
 *         &lt;element ref="{}Complete_name" minOccurs="0"/>
 *         &lt;element ref="{}Folder_name" minOccurs="0"/>
 *         &lt;element ref="{}File_name" minOccurs="0"/>
 *         &lt;element ref="{}File_extension" minOccurs="0"/>
 *         &lt;element ref="{}Format" maxOccurs="unbounded"/>
 *         &lt;element ref="{}Format_Extensions_usually_used" minOccurs="0"/>
 *         &lt;element ref="{}Commercial_name"/>
 *         &lt;element ref="{}Format_version" minOccurs="0"/>
 *         &lt;element ref="{}Format_profile" minOccurs="0"/>
 *         &lt;element ref="{}Format_settings" minOccurs="0"/>
 *         &lt;element ref="{}Format_settings__BVOP" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Format_settings__Matrix" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Format_Settings_Matrix_Data" minOccurs="0"/>
 *         &lt;element ref="{}Format_settings__GOP" minOccurs="0"/>
 *         &lt;element ref="{}Internet_media_type"/>
 *         &lt;element ref="{}Codec" maxOccurs="unbounded"/>
 *         &lt;choice>
 *           &lt;element ref="{}Codec_Extensions_usually_used" minOccurs="0"/>
 *           &lt;element ref="{}Codec_Family" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element ref="{}File_size" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}Codec_profile" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{}Codec_settings" minOccurs="0"/>
 *         &lt;element ref="{}Codec_settings__Matrix" minOccurs="0"/>
 *         &lt;element ref="{}Duration" maxOccurs="unbounded"/>
 *         &lt;choice>
 *           &lt;element ref="{}Bit_rate_mode" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}Overall_bit_rate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{}Bit_rate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{}Channel_s_" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}Maximum_bit_rate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element ref="{}Sampling_rate" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}Width" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element ref="{}Height" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}Samples_count" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{}Pixel_aspect_ratio" minOccurs="0"/>
 *         &lt;element ref="{}Display_aspect_ratio" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Frame_rate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Frame_count" minOccurs="0"/>
 *         &lt;element ref="{}Standard" minOccurs="0"/>
 *         &lt;element ref="{}Resolution" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Colorimetry" minOccurs="0"/>
 *         &lt;element ref="{}Color_space" minOccurs="0"/>
 *         &lt;element ref="{}Chroma_subsampling" minOccurs="0"/>
 *         &lt;element ref="{}Bit_depth" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Scan_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Scan_order" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Interlacement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Compression_mode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Bits__Pixel_Frame_" minOccurs="0"/>
 *         &lt;element ref="{}Delay" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Delay__origin" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{}Delay_Original" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}Delay_relative_to_video" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element ref="{}Video0_delay" minOccurs="0"/>
 *           &lt;element ref="{}Delay_Original_Settings" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{}Delay_Original_Source" minOccurs="0"/>
 *         &lt;element ref="{}Stream_size" maxOccurs="unbounded"/>
 *         &lt;element ref="{}Proportion_of_this_stream"/>
 *         &lt;choice>
 *           &lt;element ref="{}File_creation_date" minOccurs="0"/>
 *           &lt;element ref="{}Buffer_size" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element ref="{}File_creation_date__local_" minOccurs="0"/>
 *           &lt;element ref="{}intra_dc_precision" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{}File_last_modification_date" minOccurs="0"/>
 *         &lt;element ref="{}File_last_modification_date__local_" minOccurs="0"/>
 *         &lt;element ref="{}recordedDate" minOccurs="0"/>
 *         &lt;element ref="{}xyz" minOccurs="0"/>
 *         &lt;element ref="{}encodedDate" minOccurs="0"/>
 *         &lt;element ref="{}model" minOccurs="0"/>
 *         &lt;element ref="{}make" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="streamid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trackType", propOrder = {
    "count",
    "countOfStreamOfThisKind",
    "kindOfStream",
    "streamIdentifier",
    "countOfVideoStreams",
    "id",
    "countOfAudioStreams",
    "videoFormatList",
    "videoFormatWithHintList",
    "codecsVideo",
    "audioFormatList",
    "audioFormatWithHintList",
    "audioCodecs",
    "completeName",
    "folderName",
    "fileName",
    "fileExtension",
    "format",
    "formatExtensionsUsuallyUsed",
    "commercialName",
    "formatVersion",
    "formatProfile",
    "formatSettings",
    "formatSettingsBVOP",
    "formatSettingsMatrix",
    "formatSettingsMatrixData",
    "formatSettingsGOP",
    "internetMediaType",
    "codec",
    "codecExtensionsUsuallyUsed",
    "codecFamily",
    "fileSize",
    "codecProfile",
    "codecSettings",
    "codecSettingsMatrix",
    "duration",
    "bitRateMode",
    "overallBitRate",
    "bitRate",
    "channelS",
    "maximumBitRate",
    "samplingRate",
    "width",
    "height",
    "samplesCount",
    "pixelAspectRatio",
    "displayAspectRatio",
    "frameRate",
    "frameCount",
    "standard",
    "resolution",
    "colorimetry",
    "colorSpace",
    "chromaSubsampling",
    "bitDepth",
    "scanType",
    "scanOrder",
    "interlacement",
    "compressionMode",
    "bitsPixelFrame",
    "delay",
    "delayOrigin",
    "delayOriginal",
    "delayRelativeToVideo",
    "video0Delay",
    "delayOriginalSettings",
    "delayOriginalSource",
    "streamSize",
    "proportionOfThisStream",
    "fileCreationDate",
    "bufferSize",
    "fileCreationDateLocal",
    "intraDcPrecision",
    "fileLastModificationDate",
    "fileLastModificationDateLocal",
    "recordedDate",
    "xyz",
    "encodedDate",
    "model",
    "make"
})
public class TrackType
    implements Serializable
{

	private static final long serialVersionUID = 2514441374290793423L;
	@XmlElement(name = "Count", required = true)
    protected String count;
    @XmlElement(name = "Count_of_stream_of_this_kind", required = true)
    protected String countOfStreamOfThisKind;
    @XmlElement(name = "Kind_of_stream", required = true)
    protected List<String> kindOfStream;
    @XmlElement(name = "Stream_identifier", required = true)
    protected List<String> streamIdentifier;
    @XmlElement(name = "Count_of_video_streams")
    protected String countOfVideoStreams;
    @XmlElement(name = "ID")
    protected List<String> id;
    @XmlElement(name = "Count_of_audio_streams")
    protected String countOfAudioStreams;
    @XmlElement(name = "Video_Format_List")
    protected String videoFormatList;
    @XmlElement(name = "Video_Format_WithHint_List")
    protected String videoFormatWithHintList;
    @XmlElement(name = "Codecs_Video")
    protected String codecsVideo;
    @XmlElement(name = "Audio_Format_List")
    protected String audioFormatList;
    @XmlElement(name = "Audio_Format_WithHint_List")
    protected String audioFormatWithHintList;
    @XmlElement(name = "Audio_codecs")
    protected String audioCodecs;
    @XmlElement(name = "Complete_name")
    protected String completeName;
    @XmlElement(name = "Folder_name")
    protected String folderName;
    @XmlElement(name = "File_name")
    protected String fileName;
    @XmlElement(name = "File_extension")
    protected String fileExtension;
    @XmlElement(name = "Format", required = true)
    protected List<String> format;
    @XmlElement(name = "Format_Extensions_usually_used")
    protected String formatExtensionsUsuallyUsed;
    @XmlElement(name = "Commercial_name", required = true)
    protected String commercialName;
    @XmlElement(name = "Format_version")
    protected String formatVersion;
    @XmlElement(name = "Format_profile")
    protected String formatProfile;
    @XmlElement(name = "Format_settings")
    protected String formatSettings;
    @XmlElement(name = "Format_settings__BVOP")
    protected List<String> formatSettingsBVOP;
    @XmlElement(name = "Format_settings__Matrix")
    protected List<String> formatSettingsMatrix;
    @XmlElement(name = "Format_Settings_Matrix_Data")
    protected String formatSettingsMatrixData;
    @XmlElement(name = "Format_settings__GOP")
    protected String formatSettingsGOP;
    @XmlElement(name = "Internet_media_type", required = true)
    protected String internetMediaType;
    @XmlElement(name = "Codec", required = true)
    protected List<String> codec;
    @XmlElement(name = "Codec_Extensions_usually_used")
    protected String codecExtensionsUsuallyUsed;
    @XmlElement(name = "Codec_Family")
    protected String codecFamily;
    @XmlElement(name = "File_size")
    protected List<String> fileSize;
    @XmlElement(name = "Codec_profile")
    protected String codecProfile;
    @XmlElement(name = "Codec_settings")
    protected String codecSettings;
    @XmlElement(name = "Codec_settings__Matrix")
    protected String codecSettingsMatrix;
    @XmlElement(name = "Duration", required = true)
    protected List<String> duration;
    @XmlElement(name = "Bit_rate_mode")
    protected List<String> bitRateMode;
    @XmlElement(name = "Overall_bit_rate")
    protected List<String> overallBitRate;
    @XmlElement(name = "Bit_rate")
    protected List<String> bitRate;
    @XmlElement(name = "Channel_s_")
    protected List<String> channelS;
    @XmlElement(name = "Maximum_bit_rate")
    protected List<String> maximumBitRate;
    @XmlElement(name = "Sampling_rate")
    protected List<String> samplingRate;
    @XmlElement(name = "Width")
    protected List<String> width;
    @XmlElement(name = "Height")
    protected List<String> height;
    @XmlElement(name = "Samples_count")
    protected String samplesCount;
    @XmlElement(name = "Pixel_aspect_ratio")
    protected String pixelAspectRatio;
    @XmlElement(name = "Display_aspect_ratio")
    protected List<String> displayAspectRatio;
    @XmlElement(name = "Frame_rate")
    protected List<String> frameRate;
    @XmlElement(name = "Frame_count")
    protected String frameCount;
    @XmlElement(name = "Standard")
    protected String standard;
    @XmlElement(name = "Resolution")
    protected List<String> resolution;
    @XmlElement(name = "Colorimetry")
    protected String colorimetry;
    @XmlElement(name = "Color_space")
    protected String colorSpace;
    @XmlElement(name = "Chroma_subsampling")
    protected String chromaSubsampling;
    @XmlElement(name = "Bit_depth")
    protected List<String> bitDepth;
    @XmlElement(name = "Scan_type")
    protected List<String> scanType;
    @XmlElement(name = "Scan_order")
    protected List<String> scanOrder;
    @XmlElement(name = "Interlacement")
    protected List<String> interlacement;
    @XmlElement(name = "Compression_mode")
    protected List<String> compressionMode;
    @XmlElement(name = "Bits__Pixel_Frame_")
    protected String bitsPixelFrame;
    @XmlElement(name = "Delay")
    protected List<String> delay;
    @XmlElement(name = "Delay__origin")
    protected List<String> delayOrigin;
    @XmlElement(name = "Delay_Original")
    protected List<String> delayOriginal;
    @XmlElement(name = "Delay_relative_to_video")
    protected String delayRelativeToVideo;
    @XmlElement(name = "Video0_delay")
    protected String video0Delay;
    @XmlElement(name = "Delay_Original_Settings")
    protected String delayOriginalSettings;
    @XmlElement(name = "Delay_Original_Source")
    protected String delayOriginalSource;
    @XmlElement(name = "Stream_size", required = true)
    protected List<String> streamSize;
    @XmlElement(name = "Proportion_of_this_stream", required = true)
    protected String proportionOfThisStream;
    @XmlElement(name = "File_creation_date")
    protected String fileCreationDate;
    @XmlElement(name = "Buffer_size")
    protected String bufferSize;
    @XmlElement(name = "File_creation_date__local_")
    protected String fileCreationDateLocal;
    @XmlElement(name = "intra_dc_precision")
    protected String intraDcPrecision;
    @XmlElement(name = "File_last_modification_date")
    protected String fileLastModificationDate;
    @XmlElement(name = "File_last_modification_date__local_")
    protected String fileLastModificationDateLocal;
    protected String recordedDate;
    protected String xyz;
    protected String encodedDate;
    protected String model;
    protected String make;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "streamid")
    protected String streamid;

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCount(String value) {
        this.count = value;
    }

    /**
     * Gets the value of the countOfStreamOfThisKind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountOfStreamOfThisKind() {
        return countOfStreamOfThisKind;
    }

    /**
     * Sets the value of the countOfStreamOfThisKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountOfStreamOfThisKind(String value) {
        this.countOfStreamOfThisKind = value;
    }

    /**
     * Gets the value of the kindOfStream property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kindOfStream property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKindOfStream().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getKindOfStream() {
        if (kindOfStream == null) {
            kindOfStream = new ArrayList<String>();
        }
        return this.kindOfStream;
    }

    /**
     * Gets the value of the streamIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the streamIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStreamIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getStreamIdentifier() {
        if (streamIdentifier == null) {
            streamIdentifier = new ArrayList<String>();
        }
        return this.streamIdentifier;
    }

    /**
     * Gets the value of the countOfVideoStreams property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountOfVideoStreams() {
        return countOfVideoStreams;
    }

    /**
     * Sets the value of the countOfVideoStreams property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountOfVideoStreams(String value) {
        this.countOfVideoStreams = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getID() {
        if (id == null) {
            id = new ArrayList<String>();
        }
        return this.id;
    }

    /**
     * Gets the value of the countOfAudioStreams property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountOfAudioStreams() {
        return countOfAudioStreams;
    }

    /**
     * Sets the value of the countOfAudioStreams property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountOfAudioStreams(String value) {
        this.countOfAudioStreams = value;
    }

    /**
     * Gets the value of the videoFormatList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVideoFormatList() {
        return videoFormatList;
    }

    /**
     * Sets the value of the videoFormatList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVideoFormatList(String value) {
        this.videoFormatList = value;
    }

    /**
     * Gets the value of the videoFormatWithHintList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVideoFormatWithHintList() {
        return videoFormatWithHintList;
    }

    /**
     * Sets the value of the videoFormatWithHintList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVideoFormatWithHintList(String value) {
        this.videoFormatWithHintList = value;
    }

    /**
     * Gets the value of the codecsVideo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodecsVideo() {
        return codecsVideo;
    }

    /**
     * Sets the value of the codecsVideo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodecsVideo(String value) {
        this.codecsVideo = value;
    }

    /**
     * Gets the value of the audioFormatList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudioFormatList() {
        return audioFormatList;
    }

    /**
     * Sets the value of the audioFormatList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudioFormatList(String value) {
        this.audioFormatList = value;
    }

    /**
     * Gets the value of the audioFormatWithHintList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudioFormatWithHintList() {
        return audioFormatWithHintList;
    }

    /**
     * Sets the value of the audioFormatWithHintList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudioFormatWithHintList(String value) {
        this.audioFormatWithHintList = value;
    }

    /**
     * Gets the value of the audioCodecs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudioCodecs() {
        return audioCodecs;
    }

    /**
     * Sets the value of the audioCodecs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudioCodecs(String value) {
        this.audioCodecs = value;
    }

    /**
     * Gets the value of the completeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompleteName() {
        return completeName;
    }

    /**
     * Sets the value of the completeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompleteName(String value) {
        this.completeName = value;
    }

    /**
     * Gets the value of the folderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolderName() {
        return folderName;
    }

    /**
     * Sets the value of the folderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolderName(String value) {
        this.folderName = value;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the fileExtension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileExtension() {
        return fileExtension;
    }

    /**
     * Sets the value of the fileExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileExtension(String value) {
        this.fileExtension = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the format property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFormat() {
        if (format == null) {
            format = new ArrayList<String>();
        }
        return this.format;
    }

    /**
     * Gets the value of the formatExtensionsUsuallyUsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatExtensionsUsuallyUsed() {
        return formatExtensionsUsuallyUsed;
    }

    /**
     * Sets the value of the formatExtensionsUsuallyUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatExtensionsUsuallyUsed(String value) {
        this.formatExtensionsUsuallyUsed = value;
    }

    /**
     * Gets the value of the commercialName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommercialName() {
        return commercialName;
    }

    /**
     * Sets the value of the commercialName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommercialName(String value) {
        this.commercialName = value;
    }

    /**
     * Gets the value of the formatVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatVersion() {
        return formatVersion;
    }

    /**
     * Sets the value of the formatVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatVersion(String value) {
        this.formatVersion = value;
    }

    /**
     * Gets the value of the formatProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatProfile() {
        return formatProfile;
    }

    /**
     * Sets the value of the formatProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatProfile(String value) {
        this.formatProfile = value;
    }

    /**
     * Gets the value of the formatSettings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatSettings() {
        return formatSettings;
    }

    /**
     * Sets the value of the formatSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatSettings(String value) {
        this.formatSettings = value;
    }

    /**
     * Gets the value of the formatSettingsBVOP property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formatSettingsBVOP property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormatSettingsBVOP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFormatSettingsBVOP() {
        if (formatSettingsBVOP == null) {
            formatSettingsBVOP = new ArrayList<String>();
        }
        return this.formatSettingsBVOP;
    }

    /**
     * Gets the value of the formatSettingsMatrix property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formatSettingsMatrix property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormatSettingsMatrix().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFormatSettingsMatrix() {
        if (formatSettingsMatrix == null) {
            formatSettingsMatrix = new ArrayList<String>();
        }
        return this.formatSettingsMatrix;
    }

    /**
     * Gets the value of the formatSettingsMatrixData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatSettingsMatrixData() {
        return formatSettingsMatrixData;
    }

    /**
     * Sets the value of the formatSettingsMatrixData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatSettingsMatrixData(String value) {
        this.formatSettingsMatrixData = value;
    }

    /**
     * Gets the value of the formatSettingsGOP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatSettingsGOP() {
        return formatSettingsGOP;
    }

    /**
     * Sets the value of the formatSettingsGOP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatSettingsGOP(String value) {
        this.formatSettingsGOP = value;
    }

    /**
     * Gets the value of the internetMediaType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternetMediaType() {
        return internetMediaType;
    }

    /**
     * Sets the value of the internetMediaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternetMediaType(String value) {
        this.internetMediaType = value;
    }

    /**
     * Gets the value of the codec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the codec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCodec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCodec() {
        if (codec == null) {
            codec = new ArrayList<String>();
        }
        return this.codec;
    }

    /**
     * Gets the value of the codecExtensionsUsuallyUsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodecExtensionsUsuallyUsed() {
        return codecExtensionsUsuallyUsed;
    }

    /**
     * Sets the value of the codecExtensionsUsuallyUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodecExtensionsUsuallyUsed(String value) {
        this.codecExtensionsUsuallyUsed = value;
    }

    /**
     * Gets the value of the codecFamily property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodecFamily() {
        return codecFamily;
    }

    /**
     * Sets the value of the codecFamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodecFamily(String value) {
        this.codecFamily = value;
    }

    /**
     * Gets the value of the fileSize property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fileSize property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFileSize().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFileSize() {
        if (fileSize == null) {
            fileSize = new ArrayList<String>();
        }
        return this.fileSize;
    }

    /**
     * Gets the value of the codecProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodecProfile() {
        return codecProfile;
    }

    /**
     * Sets the value of the codecProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodecProfile(String value) {
        this.codecProfile = value;
    }

    /**
     * Gets the value of the codecSettings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodecSettings() {
        return codecSettings;
    }

    /**
     * Sets the value of the codecSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodecSettings(String value) {
        this.codecSettings = value;
    }

    /**
     * Gets the value of the codecSettingsMatrix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodecSettingsMatrix() {
        return codecSettingsMatrix;
    }

    /**
     * Sets the value of the codecSettingsMatrix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodecSettingsMatrix(String value) {
        this.codecSettingsMatrix = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the duration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDuration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDuration() {
        if (duration == null) {
            duration = new ArrayList<String>();
        }
        return this.duration;
    }

    /**
     * Gets the value of the bitRateMode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bitRateMode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBitRateMode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getBitRateMode() {
        if (bitRateMode == null) {
            bitRateMode = new ArrayList<String>();
        }
        return this.bitRateMode;
    }

    /**
     * Gets the value of the overallBitRate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the overallBitRate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOverallBitRate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOverallBitRate() {
        if (overallBitRate == null) {
            overallBitRate = new ArrayList<String>();
        }
        return this.overallBitRate;
    }

    /**
     * Gets the value of the bitRate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bitRate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBitRate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getBitRate() {
        if (bitRate == null) {
            bitRate = new ArrayList<String>();
        }
        return this.bitRate;
    }

    /**
     * Gets the value of the channelS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the channelS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChannelS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getChannelS() {
        if (channelS == null) {
            channelS = new ArrayList<String>();
        }
        return this.channelS;
    }

    /**
     * Gets the value of the maximumBitRate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the maximumBitRate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMaximumBitRate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMaximumBitRate() {
        if (maximumBitRate == null) {
            maximumBitRate = new ArrayList<String>();
        }
        return this.maximumBitRate;
    }

    /**
     * Gets the value of the samplingRate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the samplingRate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSamplingRate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSamplingRate() {
        if (samplingRate == null) {
            samplingRate = new ArrayList<String>();
        }
        return this.samplingRate;
    }

    /**
     * Gets the value of the width property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the width property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWidth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getWidth() {
        if (width == null) {
            width = new ArrayList<String>();
        }
        return this.width;
    }

    /**
     * Gets the value of the height property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the height property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHeight().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getHeight() {
        if (height == null) {
            height = new ArrayList<String>();
        }
        return this.height;
    }

    /**
     * Gets the value of the samplesCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSamplesCount() {
        return samplesCount;
    }

    /**
     * Sets the value of the samplesCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSamplesCount(String value) {
        this.samplesCount = value;
    }

    /**
     * Gets the value of the pixelAspectRatio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPixelAspectRatio() {
        return pixelAspectRatio;
    }

    /**
     * Sets the value of the pixelAspectRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPixelAspectRatio(String value) {
        this.pixelAspectRatio = value;
    }

    /**
     * Gets the value of the displayAspectRatio property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the displayAspectRatio property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisplayAspectRatio().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDisplayAspectRatio() {
        if (displayAspectRatio == null) {
            displayAspectRatio = new ArrayList<String>();
        }
        return this.displayAspectRatio;
    }

    /**
     * Gets the value of the frameRate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the frameRate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFrameRate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFrameRate() {
        if (frameRate == null) {
            frameRate = new ArrayList<String>();
        }
        return this.frameRate;
    }

    /**
     * Gets the value of the frameCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameCount() {
        return frameCount;
    }

    /**
     * Sets the value of the frameCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameCount(String value) {
        this.frameCount = value;
    }

    /**
     * Gets the value of the standard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandard() {
        return standard;
    }

    /**
     * Sets the value of the standard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandard(String value) {
        this.standard = value;
    }

    /**
     * Gets the value of the resolution property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resolution property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResolution().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getResolution() {
        if (resolution == null) {
            resolution = new ArrayList<String>();
        }
        return this.resolution;
    }

    /**
     * Gets the value of the colorimetry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorimetry() {
        return colorimetry;
    }

    /**
     * Sets the value of the colorimetry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorimetry(String value) {
        this.colorimetry = value;
    }

    /**
     * Gets the value of the colorSpace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorSpace() {
        return colorSpace;
    }

    /**
     * Sets the value of the colorSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorSpace(String value) {
        this.colorSpace = value;
    }

    /**
     * Gets the value of the chromaSubsampling property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChromaSubsampling() {
        return chromaSubsampling;
    }

    /**
     * Sets the value of the chromaSubsampling property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChromaSubsampling(String value) {
        this.chromaSubsampling = value;
    }

    /**
     * Gets the value of the bitDepth property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bitDepth property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBitDepth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getBitDepth() {
        if (bitDepth == null) {
            bitDepth = new ArrayList<String>();
        }
        return this.bitDepth;
    }

    /**
     * Gets the value of the scanType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scanType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScanType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getScanType() {
        if (scanType == null) {
            scanType = new ArrayList<String>();
        }
        return this.scanType;
    }

    /**
     * Gets the value of the scanOrder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scanOrder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScanOrder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getScanOrder() {
        if (scanOrder == null) {
            scanOrder = new ArrayList<String>();
        }
        return this.scanOrder;
    }

    /**
     * Gets the value of the interlacement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interlacement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterlacement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getInterlacement() {
        if (interlacement == null) {
            interlacement = new ArrayList<String>();
        }
        return this.interlacement;
    }

    /**
     * Gets the value of the compressionMode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compressionMode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompressionMode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCompressionMode() {
        if (compressionMode == null) {
            compressionMode = new ArrayList<String>();
        }
        return this.compressionMode;
    }

    /**
     * Gets the value of the bitsPixelFrame property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBitsPixelFrame() {
        return bitsPixelFrame;
    }

    /**
     * Sets the value of the bitsPixelFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBitsPixelFrame(String value) {
        this.bitsPixelFrame = value;
    }

    /**
     * Gets the value of the delay property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delay property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelay().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDelay() {
        if (delay == null) {
            delay = new ArrayList<String>();
        }
        return this.delay;
    }

    /**
     * Gets the value of the delayOrigin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delayOrigin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelayOrigin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDelayOrigin() {
        if (delayOrigin == null) {
            delayOrigin = new ArrayList<String>();
        }
        return this.delayOrigin;
    }

    /**
     * Gets the value of the delayOriginal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delayOriginal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelayOriginal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDelayOriginal() {
        if (delayOriginal == null) {
            delayOriginal = new ArrayList<String>();
        }
        return this.delayOriginal;
    }

    /**
     * Gets the value of the delayRelativeToVideo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelayRelativeToVideo() {
        return delayRelativeToVideo;
    }

    /**
     * Sets the value of the delayRelativeToVideo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelayRelativeToVideo(String value) {
        this.delayRelativeToVideo = value;
    }

    /**
     * Gets the value of the video0Delay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVideo0Delay() {
        return video0Delay;
    }

    /**
     * Sets the value of the video0Delay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVideo0Delay(String value) {
        this.video0Delay = value;
    }

    /**
     * Gets the value of the delayOriginalSettings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelayOriginalSettings() {
        return delayOriginalSettings;
    }

    /**
     * Sets the value of the delayOriginalSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelayOriginalSettings(String value) {
        this.delayOriginalSettings = value;
    }

    /**
     * Gets the value of the delayOriginalSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelayOriginalSource() {
        return delayOriginalSource;
    }

    /**
     * Sets the value of the delayOriginalSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelayOriginalSource(String value) {
        this.delayOriginalSource = value;
    }

    /**
     * Gets the value of the streamSize property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the streamSize property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStreamSize().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getStreamSize() {
        if (streamSize == null) {
            streamSize = new ArrayList<String>();
        }
        return this.streamSize;
    }

    /**
     * Gets the value of the proportionOfThisStream property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProportionOfThisStream() {
        return proportionOfThisStream;
    }

    /**
     * Sets the value of the proportionOfThisStream property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProportionOfThisStream(String value) {
        this.proportionOfThisStream = value;
    }

    /**
     * Gets the value of the fileCreationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileCreationDate() {
        return fileCreationDate;
    }

    /**
     * Sets the value of the fileCreationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileCreationDate(String value) {
        this.fileCreationDate = value;
    }

    /**
     * Gets the value of the bufferSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBufferSize() {
        return bufferSize;
    }

    /**
     * Sets the value of the bufferSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBufferSize(String value) {
        this.bufferSize = value;
    }

    /**
     * Gets the value of the fileCreationDateLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileCreationDateLocal() {
        return fileCreationDateLocal;
    }

    /**
     * Sets the value of the fileCreationDateLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileCreationDateLocal(String value) {
        this.fileCreationDateLocal = value;
    }

    /**
     * Gets the value of the intraDcPrecision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntraDcPrecision() {
        return intraDcPrecision;
    }

    /**
     * Sets the value of the intraDcPrecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntraDcPrecision(String value) {
        this.intraDcPrecision = value;
    }

    /**
     * Gets the value of the fileLastModificationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileLastModificationDate() {
        return fileLastModificationDate;
    }

    /**
     * Sets the value of the fileLastModificationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileLastModificationDate(String value) {
        this.fileLastModificationDate = value;
    }

    /**
     * Gets the value of the fileLastModificationDateLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileLastModificationDateLocal() {
        return fileLastModificationDateLocal;
    }

    /**
     * Sets the value of the fileLastModificationDateLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileLastModificationDateLocal(String value) {
        this.fileLastModificationDateLocal = value;
    }

    /**
     * Gets the value of the recordedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordedDate() {
        return recordedDate;
    }

    /**
     * Sets the value of the recordedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordedDate(String value) {
        this.recordedDate = value;
    }

    /**
     * Gets the value of the xyz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXyz() {
        return xyz;
    }

    /**
     * Sets the value of the xyz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXyz(String value) {
        this.xyz = value;
    }

    /**
     * Gets the value of the encodedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncodedDate() {
        return encodedDate;
    }

    /**
     * Sets the value of the encodedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncodedDate(String value) {
        this.encodedDate = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the make property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMake() {
        return make;
    }

    /**
     * Sets the value of the make property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMake(String value) {
        this.make = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the streamid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreamid() {
        return streamid;
    }

    /**
     * Sets the value of the streamid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreamid(String value) {
        this.streamid = value;
    }

    public List<String> getId() {
      return id;
    }

    public void setId(List<String> id) {
      this.id = id;
    }

}
