//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-03/09/2011 06:46 PM(foreman)-)
//


package com.vz.dam.domain;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UpdateAssetsRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateAssetsRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="assetsDetail" type="{http://DAMAssetManagerHelperLibrary}DAMAssetsDetails" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateAssetsRequest", propOrder = {
    "assetsDetail"
})
public class UpdateAssetsRequest
    implements Serializable
{

    protected DAMAssetsDetails assetsDetail;

    /**
     * Gets the value of the assetsDetail property.
     * 
     * @return
     *     possible object is
     *     {@link DAMAssetsDetails }
     *     
     */
    public DAMAssetsDetails getAssetsDetail() {
        return assetsDetail;
    }

    /**
     * Sets the value of the assetsDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link DAMAssetsDetails }
     *     
     */
    public void setAssetsDetail(DAMAssetsDetails value) {
        this.assetsDetail = value;
    }

}
